spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/video?authSource=admin
  datasource:
      oss:
          provider: minio
          endpoint: http://localhost:9000
          access-key: Y7K9YOfQJv5DHZkcNGeS
          secret-key: rV2Svk4rSyfLe6Cf8MhoZ8NaDR7En4uLYgQnLotx
          bucket: raw
          region: ap-southeast-2
          object-dir-prefix: videos
