name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.YOUPIPE_DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/youpipe:1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/youpipe:latest

      - name: Update Docker Hub Repository Description and Maintainers
        run: |
          curl -X POST "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/youpipe/" \
               -H "Authorization: JWT ${TOKEN}" \
               -d '{"full_description": "YouPipe, an experimental YouTube clone", "maintainers": ["Jarvan Lee <jarvan-jobs@outlook.com>"]}'
        env:
          TOKEN: ${{ secrets.DOCKER_HUB_API_TOKEN }}

